version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: traject
    versions:
    - 3.5.0
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
  - dependency-name: rubocop
    versions:
    - 1.9.0
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
