services:
  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
  solr:
    build:
      context: .
      dockerfile: .docker/solr/Dockerfile
    ports:
      - "${SOLR_PORT}:8983"
    environment:
      ZK_HOST: "zookeeper:2181"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight
      - /opt/solr/configs/tul_cob-catalog-solr
      - "-Xms256m"
      - "-Xmx512m"
