version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  coveralls: coveralls/coveralls@2.2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0-node
      - image: zookeeper:3.7
        name: zoo
        environment:
          ZOO_CFG_EXTRA: "4lw.commands.whitelist=mntr,conf,ruok"
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: solr:8.11.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          ZK_HOST: "zoo:2181"
          docker_layer_caching: false
    executor: ruby/default
    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - run: bundle install

      - run:
          name: Upload security.json file to solr container
          command: docker cp .circleci/security.json  $(docker ps | grep solr | cut -d ' ' -f 1):/security.json

      - run:
          name: Upload security.json to Zookeeper
          command:  docker exec $(docker ps | grep solr | cut -d ' ' -f 1) bin/solr zk cp /security.json  zk:/security.json

      - run:
          name: lint
          command: bundle exec rubocop

      - run:
          name: test
          command: bundle exec rake

      - coveralls/upload:
          coverage_file: ./coverage/lcov/project.lcov

      - run:
          name: Install Solr Documents
          command: make load-data

      - run:
          name: Run relevancy Tests
          command: make test-relevancy
