version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: circleci/jruby:9.2.19.0
      - image: zookeeper:3.7
        name: zoo
        environment:
          ZOO_CFG_EXTRA: "4lw.commands.whitelist=mntr,conf,ruok"
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: solr:8.3
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          ZK_HOST: "zoo:2181"
    executor: ruby/default
    steps:
      - checkout

      # https://discuss.circleci.com/t/how-to-get-ffi-working-on-ruby-2-7-2-image/37787/2
      - run:
          name: fix ffi not installing
          command: sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

      - run:
          name: Which bundler?
          command: bundle -v

      - ruby/bundle-install

      - run:
          name: lint
          command: bundle exec rubocop

      - run:
          name: test
          command: bundle exec rake

      - coveralls/upload:
          path_to_lcov: ./coverage/lcov/project.lcov

      - run:
          name: Install Solr Documents
          command: make load-data

      - run:
          name: Run relevancy Tests
          command: make test-relevancy
